import 'club_model.dart';

final List<ClubModel> mockClubs = [
  ClubModel(
    abbr: 'OSS',
    name: 'OSS Club',
    fullForm: 'Open Source Software Club',
    img: 'assets/clublogos/oss.svg',
    desc: 'Encouraging students to contribute to open source projects and learn collaborative software development.',
    focusAreas: ['Open source contribution workflows', 'Contribution (Git/Github)'],
    activities: ['INNERVE', 'FSOC', 'Graphica', 'Spark', 'Internal SIH', 'Replica'],
    media: ['https://images.unsplash.com/photo-1607569490015-7101095605ed?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1517433456452-f9633a875f6f?auto=format&fit=crop&w=800&q=80'],
    who: 'FE,SE',
    keywords: ['OSS'],
  ),
  ClubModel(
    abbr: 'GDG',
    name: 'GDG AIT Pune',
    fullForm: 'Google Developer Group',
    img: 'assets/clublogos/google-developers.svg',
    desc: 'Community-driven developer group focused on practical developer skills and technology learning.',
    focusAreas: ['Web & mobile development', 'Cloud and architecture', 'Developer tooling and best practices'],
    activities: ['Frontend Jams', 'Backend Jams', 'FSOC', 'Enliven', 'Google Cloud Workshop', 'Android Development Session'],
    media: ['https://images.unsplash.com/photo-1531297461136-82lw9b44d940?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1517433456452-f9633a875f6f?auto=format&fit=crop&w=800&q=80'],
    who: 'FE,SE',
    keywords: ['GDG'],
  ),
  ClubModel(
    abbr: 'CP',
    name: 'CP Club',
    fullForm: 'Competitive Programming',
    img: 'assets/clublogos/cp.svg',
    desc: 'Focused training and practice for programming contests and technical interviews.',
    focusAreas: ['Data structures & algorithms', 'Problem-solving strategies', 'Contest practice and timing'],
    activities: ['CODEFT 4.0', 'CRACK 5.1', 'CRACK 5.2', 'KICKSTARTER'],
    media: ['https://images.unsplash.com/photo-1531297461136-82lw9b44d940?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1517433456452-f9633a875f6f?auto=format&fit=crop&w=800&q=80'],
    who: 'FE,SE',
    keywords: ['CP'],
  ),
  ClubModel(
    abbr: 'PR',
    name: 'PR Cell',
    fullForm: 'Public Relations Cell',
    img: 'assets/clublogos/pr.svg',
    desc: 'Handles campus branding, outreach, media communication, and event promotions.',
    focusAreas: ['Branding & communication', 'Social media management', 'Event marketing'],
    activities: ['Campus outreach', 'Event promotions', 'Media coordination'],
    who: 'FE,SE',
    keywords: ['PR'],
  ),
  ClubModel(
    abbr: 'ECELL',
    name: 'E-Cell',
    fullForm: 'Entrepreneurship Cell',
    img: 'assets/clublogos/ecell.svg',
    desc: 'Promotes entrepreneurship, innovation, and startup culture among students.',
    focusAreas: ['Startup fundamentals', 'Ideation & innovation', 'Business models & pitching'],
    activities: ['Startup Bootcamp', 'Pitch Deck Workshop', 'Incubation support'],
    who: 'FE,SE',
    keywords: ['ECELL'],
  ),
  ClubModel(
    abbr: 'GDXR',
    name: 'GDXR',
    fullForm: 'Game Dev & Extended Reality Club',
    img: 'assets/clublogos/gdxr.svg',
    desc: 'Dedicated to game development, AR/VR technologies, and immersive experiences.',
    focusAreas: ['Game engines (Unity/Unreal)', 'AR/VR development', '3D modeling & interaction'],
    activities: ['● GameJam', '● XR Workshop', '● Dev Sprints'],
    who: 'FE,SE',
    keywords: ['GDXR'],
  ),
  ClubModel(
    abbr: 'ISDF',
    name: 'ISDF',
    fullForm: 'Information Security & Digital Forensics Club',
    img: 'assets/clublogos/isdf.svg',
    desc: 'Focuses on cybersecurity, ethical hacking, and digital forensics skills.',
    focusAreas: ['Ethical hacking', 'Network & system security', 'Digital forensics'],
    activities: ['CTF Challenges', 'Cybersecurity Workshops', 'Forensics Lab Training'],
    who: 'FE,SE',
    keywords: ['ISDF'],
  ),
  ClubModel(
    abbr: 'RND',
    name: 'RnD Cell',
    fullForm: 'Research & Development Cell',
    img: 'assets/clublogos/rnd.svg',
    desc: 'Encourages research-thinking, publications, and innovation-driven projects.',
    focusAreas: ['Research methodology', 'Academic writing', 'Innovation projects'],
    activities: ['Research Paper Workshops', 'Project Mentorship', 'Publication Guidance'],
    who: 'FE,SE',
    keywords: ['RND'],
  ),
  ClubModel(
    abbr: 'CYCLE',
    name: 'Cycling Club',
    img: 'assets/clublogos/cycling.svg',
    desc: 'Promotes fitness and community through regular cycling meetups and long rides.',
    focusAreas: ['Fitness & endurance', 'Group riding skills', 'Safe cycling practices'],
    activities: ['Weekend Rides', 'Long-Distance Trails', 'Cycling Awareness Events'],
    who: 'FE,SE',
    keywords: ['CYCLE'],
  ),
  ClubModel(
    abbr: 'NSS',
    name: 'NSS',
    fullForm: 'National Service Scheme',
    img: 'assets/clublogos/oss.svg',
    desc: 'A volunteer organisation dedicated to social service and community development.',
    focusAreas: ['Community service', 'Social awareness', 'Rural development'],
    activities: ['Blood Donation Camps', 'Cleanliness Drives', 'Social Outreach Programs'],
    who: 'FE,SE',
    keywords: ['NSS'],
  ),
  ClubModel(
    abbr: 'NATURE',
    name: 'Nature’s Club',
    img: 'assets/clublogos/oss.svg',
    desc: 'Encourages environmental conservation, sustainability, and nature awareness.',
    focusAreas: ['Environmental protection', 'Sustainability projects', 'Wildlife awareness'],
    activities: ['Plantation Drives', 'Nature Walks', 'Eco-Awareness Campaigns'],
    who: 'FE,SE',
    keywords: ['NATURE'],
  ),
  ClubModel(
    abbr: 'MAG',
    name: 'Magboard',
    fullForm: 'Magazine & Editorial Board',
    img: 'assets/clublogos/magboard.svg',
    desc: 'Manages college magazine, newsletter writing, and creative editorial work.',
    focusAreas: ['Creative writing', 'Editing & publishing', 'Journalism & reporting'],
    activities: ['College Magazine', 'Newsletter Editing', 'Writing Competitions'],
    who: 'FE,SE',
    keywords: ['MAG'],
  ),
  ClubModel(
    abbr: 'TECH',
    name: 'Technical Board',
    img: 'assets/clublogos/oss.svg',
    desc: 'Central body managing all technical clubs and driving innovation, tech events, and project-based learning across the institute.',
    focusAreas: ['Coordination of technical clubs', 'Organizing hackathons & tech festivals', 'Promoting research, innovation, and development'],
    activities: ['Institute Tech Fest', 'Inter-Club Hackathons', 'Technical Workshops & Seminars'],
    who: 'FE,SE',
    keywords: ['TECH'],
  ),
  ClubModel(
    abbr: 'CUL',
    name: 'Cultural Board',
    img: 'assets/clublogos/oss.svg',
    desc: 'Oversees cultural clubs and promotes art, creativity, and cultural expression through events and performances.',
    focusAreas: ['Literary & creative arts', 'Performing arts (dance, music, drama)', 'Cultural festivals & talent showcases'],
    activities: ['Annual Cultural Fest', 'Talent Nights', 'Inter-College Cultural Events'],
    who: 'FE,SE',
    keywords: ['CUL'],
  ),
];
